version: '3.7'

services :

  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    networks:
      - main
    env_file:
      - .env.local
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    networks:
      - main
    depends_on:
      - db
    env_file:
      - .env.local

networks:
  main:
